packages:
  - docs-site

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  '@better-auth/utils': 0.4.0
  '@better-fetch/fetch': 1.1.21
  typescript: ^5.9.3

catalogs:
  react19:
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4
  tailwind:
    '@tailwindcss/postcss': ^4.2.1
    tailwindcss: ^4.2.1
    tailwindcss-animate: ^1.0.7
